package com.cm4j.test.guava.consist.entity;

// Generated 2013-2-27 11:42:21 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.cm4j.test.guava.consist.CacheEntry;

/**
 * FieldFlagSituation generated by hbm2java
 */
@Entity
@Table(name = "field_flag_situation")
public class FieldFlagSituation extends CacheEntry implements IEntity {

	private static final long serialVersionUID = 1L;

	/**
	 * 空闲 - 0
	 */
	public static final String FLAG_STATE_IDLE = "0";
	/**
	 * 被占领 - 1
	 */
	public static final String FLAG_STATE_FLAGED = "1";

	private Integer NPlayerId;
	private Integer NFlagedId;
	private String SFlagState;
	private Date DLastTime;
	private Short NAddition;

	public FieldFlagSituation() {
	}

	@Id
	@Column(name = "n_player_id", unique = true, nullable = false)
	public Integer getNPlayerId() {
		return this.NPlayerId;
	}

	public void setNPlayerId(Integer NPlayerId) {
		this.NPlayerId = NPlayerId;
	}

	@Column(name = "n_flaged_id", nullable = false)
	public Integer getNFlagedId() {
		return this.NFlagedId;
	}

	public void setNFlagedId(Integer NFlagedId) {
		this.NFlagedId = NFlagedId;
	}

	@Column(name = "s_flag_state", nullable = false, length = 1)
	public String getSFlagState() {
		return this.SFlagState;
	}

	public void setSFlagState(String SFlagState) {
		this.SFlagState = SFlagState;
	}

	@Column(name = "d_last_time", nullable = false)
	public Date getDLastTime() {
		return this.DLastTime;
	}

	public void setDLastTime(Date DLastTime) {
		this.DLastTime = DLastTime;
	}

	@Column(name = "n_addition", nullable = false)
	public Short getNAddition() {
		return this.NAddition;
	}

	public void setNAddition(Short NAddition) {
		this.NAddition = NAddition;
	}

	@Override
	public IEntity parseEntity() {
		return this;
	}
}
