package com.cm4j.test.guava.consist.entity;

// Generated 2013-2-17 11:30:58 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestName generated by hbm2java
 */
@Entity
@Table(name = "test_name")
public class TestName implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer NId;
	private String SName;

	public TestName() {
	}

	public TestName(Integer NId, String SName) {
		this.NId = NId;
		this.SName = SName;
	}

	@Id
	@Column(name = "n_id", unique = true, nullable = false)
	public Integer getNId() {
		return this.NId;
	}

	public void setNId(Integer NId) {
		this.NId = NId;
	}

	@Column(name = "s_name", nullable = false, length = 15)
	public String getSName() {
		return this.SName;
	}

	public void setSName(String SName) {
		this.SName = SName;
	}

}
