package com.cm4j.test.guava.consist.entity;

// Generated 2013-7-16 19:15:22 by Hibernate Tools 3.4.0.CR1

import com.cm4j.test.guava.consist.cc.CacheEntry;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TmpFhhd generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tmp_fhhd")
public class TmpFhhd extends CacheEntry implements IEntity, Cloneable {

	private Integer NPlayerId;
	private Integer NCurToken;
	private Integer NRedToken;
	private String SRewards;

	public TmpFhhd() {
	}

	public TmpFhhd(Integer NPlayerId) {
		this.NPlayerId = NPlayerId;
	}

	public TmpFhhd(Integer NPlayerId, Integer NCurToken, Integer NRedToken, String SRewards) {
		this.NPlayerId = NPlayerId;
		this.NCurToken = NCurToken;
		this.NRedToken = NRedToken;
		this.SRewards = SRewards;
	}

	@Id
	@Column(name = "n_player_id", unique = true, nullable = false)
	public Integer getNPlayerId() {
		return this.NPlayerId;
	}

	public void setNPlayerId(Integer NPlayerId) {
		this.NPlayerId = NPlayerId;
	}

	@Column(name = "n_cur_token")
	public Integer getNCurToken() {
		return this.NCurToken;
	}

	public void setNCurToken(Integer NCurToken) {
		this.NCurToken = NCurToken;
	}

	@Column(name = "n_red_token")
	public Integer getNRedToken() {
		return this.NRedToken;
	}

	public void setNRedToken(Integer NRedToken) {
		this.NRedToken = NRedToken;
	}

	@Column(name = "s_rewards", length = 50)
	public String getSRewards() {
		return this.SRewards;
	}

	public void setSRewards(String SRewards) {
		this.SRewards = SRewards;
	}

	@Override
	public IEntity parseEntity() {
		try {
			return (IEntity) this.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}

	public void increaseValue() {
		this.NCurToken++;
	}

}
