package com.cm4j.test.guava.consist.entity;

// Generated 2013-10-11 18:21:27 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TmpListMultikeyPK generated by hbm2java
 */
@Embeddable
public class TmpListMultikeyPK implements java.io.Serializable {

	private int NPlayerId;
	private int NType;

	public TmpListMultikeyPK() {
	}

	public TmpListMultikeyPK(int NPlayerId, int NType) {
		this.NPlayerId = NPlayerId;
		this.NType = NType;
	}

	@Column(name = "n_player_id", nullable = false)
	public int getNPlayerId() {
		return this.NPlayerId;
	}

	public void setNPlayerId(int NPlayerId) {
		this.NPlayerId = NPlayerId;
	}

	@Column(name = "n_type", nullable = false)
	public int getNType() {
		return this.NType;
	}

	public void setNType(int NType) {
		this.NType = NType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpListMultikeyPK))
			return false;
		TmpListMultikeyPK castOther = (TmpListMultikeyPK) other;

		return (this.getNPlayerId() == castOther.getNPlayerId())
				&& (this.getNType() == castOther.getNType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNPlayerId();
		result = 37 * result + this.getNType();
		return result;
	}

}
